// components/CarData.ts
export const cars = [
    {
      name: "Toyota Corolla",
      price: "PKR 59.7 - 75.5 lacs",
      reviews: 621,
      rating: 3,
      imageUrl: "/images/Corolla-X-Cars.jpg",
      route: "toyota-corolla",
      description: "Toyota Corolla is a reliable car known for its comfort and fuel efficiency.",
      numberOfDoors: 4,
      engine: "1800 CC",
      condition: "8.5 / 10",
      driven: "9,500 KM",
      suspensionType: "Soft Suspension",
      average: "13 Km per liter",
      transmission: "Automatic",
      fuelType: "High Octane",
    },
    {
      name: "Suzuki Alto",
      price: "PKR 23.3 - 30.5 lacs",
      reviews: 199,
      rating: 4,
      imageUrl: "/images/Suzuki_Alto.png",
      route: "suzuki-alto",
      description: "Suzuki Alto is a compact and affordable car, perfect for city driving.",
      numberOfDoors: 4,
      engine: "660 CC",
      condition: "8 / 10",
      driven: "20,000 KM",
      suspensionType: "Standard Suspension",
      average: "20 Km per liter",
      transmission: "Manual",
      fuelType: "Petrol",
    },
    {
      name: "Honda City",
      price: "PKR 46.5 - 58.5 lacs",
      reviews: 458,
      rating: 3,
      imageUrl: "/images/Honda_City.jpg",
      route: "honda-city",
      description: "Honda City is a spacious car with a stylish design and powerful engine.",
      numberOfDoors: 4,
      engine: "1500 CC",
      condition: "9 / 10",
      driven: "12,000 KM",
      suspensionType: "Soft Suspension",
      average: "15 Km per liter",
      transmission: "Automatic",
      fuelType: "Petrol",
    },
    {
      name: "Honda Civic",
      price: "PKR 86.6 - 99.0 lacs",
      reviews: 357,
      rating: 3,
      imageUrl: "/images/Honda_civic.jpg",
      route: "honda-civic",
      description: "Honda Civic is a popular sedan with a sleek design and advanced features.",
      numberOfDoors: 4,
      engine: "1800 CC",
      condition: "9.5 / 10",
      driven: "10,500 KM",
      suspensionType: "Soft Suspension",
      average: "12 Km per liter",
      transmission: "Automatic",
      fuelType: "High Octane",
    },
  ];
  